services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: lawfirm_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "lawfirm_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: ./avukatlik_sitesi
    container_name: django_backend
    volumes:
      - ./avukatlik_sitesi:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./avukatlik_sitesi/.env

volumes:
  postgres_data:
