trigger:
  branches:
    include:
      - main

variables:
  imageName: lawyer-backend
  environmentName: backend

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: Docker@2
    inputs:
      containerRegistry: "your-azure-acr-connection" # Azure Service Connection adı
      repository: "$(imageName)"
      command: "buildAndPush"
      Dockerfile: "**/Dockerfile"
      tags: |
        $(Build.BuildId)

  - task: AzureWebAppContainer@1
    inputs:
      azureSubscription: "your-azure-subscription"
      appName: "lawyer-backend-app"
      containers: "youracrname.azurecr.io/$(imageName):$(Build.BuildId)"
